<?php

namespace AppBundle\Repository;

/**
 * FruitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FruitRepository extends \Doctrine\ORM\EntityRepository
{
  // nous ajouterons ici nos méthodes personnalisées de
  // récupération de données
}
