<?php

namespace AppBundle\Repository;

/**
 * RetailorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailorRepository extends \Doctrine\ORM\EntityRepository
{
}
